name: tester
description: Test Uygulaması

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  wikipedia: ^0.0.7
#  neumorphic_widget: ^0.0.1
#  neumorphic_button: ^0.0.1+2
#  flutter_neumorphic: ^3.2.0
#  reactive_cupertino_text_field: ^0.5.0
#  flutter_svg: ^2.0.1
#  http: ^0.13.5
#  xml: ^6.2.2
#  xml2json: ^5.0.0
  flutter_secure_storage: ^8.0.0
  dio: ^5.0.1
  connectivity_plus: ^3.0.3
  internet_connection_checker: ^1.0.0+1
  mailer: ^6.0.0
  flutter_riverpod: ^2.0.2


  flutter_local_notifications: ^15.1.1
  flutter_background_service: ^5.0.1
  #firebase_messaging: ^14.6.9
  #flutter_background: ^1.2.0
  signalr_core: ^1.1.1
  permission_handler: ^11.0.1
  workmanager: ^0.5.2


#  audioplayers: ^3.0.1
#  flutter_echarts: ^2.4.0
#  fl_chart: ^0.61.0
#  assets_audio_player: ^3.0.6
#  syncfusion_flutter_charts: ^20.4.52
  fluttertoast: ^8.0.7
#  carousel_slider: ^4.2.1
#  firebase_database: ^10.0.16
  path_provider: ^2.0.14
#  flutter_audio_query: ^0.3.4
  flutter_lints: ^2.0.0
  pdf: ^3.10.4
  #html: ^0.15.2
#  flute_music_player: ^0.0.6

  cupertino_icons: ^1.0.2
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
#  license_generator: ^1.0.5
#  flutter_oss_licenses: ^2.0.1
#  flutter_launcher_name: ^0.0.1
#  flutter_launcher_icons: ^0.13.1

#dependency_overrides:
#  yaml: ^3.1.1

#flutter_icons:
#  android: true
#  ios: true
#  remove_alpha_ios: true
#  image_path: "lib/Assets/logo/logo.png"
#  adaptive_icon_background: "#222222"
#  #adaptive_icon_background: "lib/Assets/logo/back.png"
#  adaptive_icon_foreground: "lib/Assets/logo/fore.png"
#  web:
#    generate: true
#    image_path: "lib/Assets/logo/fore.png"
#  windows:
#    generate: true
#    image_path: "lib/Assets/logo/logo.png"
#  macos:
#    generate: true
#    image_path: "lib/Assets/logo/fore.png"

#flutter_launcher_name:
#  name: "denemeler2"

flutter:
  uses-material-design: true

  assets:
    - lib/Assets/alt_bar/
    - lib/Assets/iconlar/
    - lib/Assets/sesler/
    - lib/Assets/pdf/
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
